### ISSUE TITLE
API 

### ISSUE THREAD

**Issue by ghost** [jihoon1990/Coiner#3]
I am from China,I apply for an API in Bithumb, However,when I visit the private  method ,it tells me 
"Invalid secretkey",I am sure it is right,besides,I have fixed the  API with ip in China,I use the demo
python3 program provided by Bithumb..
    can you give me some advice?

**Comment by jihoonerd** [comment]
You should make `account_info.py` at root directory and include variables like the form below:
```python
api_key = "YOUR API KEY"
api_secret = "YOUR API SECRET KEY"
```
Also, this `api_key` and `api_secret` should be handled by the method `xcoinApiCall` which is included in  `xcoin_api_client.py`
