### ISSUE TITLE
About cancel orders

### ISSUE THREAD

**Issue by LinLL** [jihoon1990/Coiner#4]
Hi,
Recently I wrappered bithumb API .But the problem about cancel orders occurded on.
The url is [https://api.bithumb.com/trade/cancel], whatever parameters of type I submit,the error code {'status': '5600', 'message': '거래 체결내역이 존재하지 않습니다.'} is always hit me.
Would you mind give me some suggestions?
.

**Comment by jihoonerd** [comment]
Hello, possibly API interface could be different by country. Could you leave your code for canceling contracts?

**Comment by LinLL** [comment]
I used the official API of bithumb, the others is successful besides cancel and order detials.
I used the  xcoinApiCall(self, endpoint, rgParams) to  call the cancel api , parameters is {'order_id':1513778076667335,'type':'ask','currency':'BTC'}  the order_id is the last order return by order API.

**Comment by jihoonerd** [comment]
First of all, the message you've got, {'status': '5600', 'message': '거래 체결내역이 존재하지 않습니다.'} says "There is no closed contract for the order_id", so I suggest you check the existence of the contract number. Also error code 5600 could occur when Bithumb server is busy.

FYI: For now (2017-12-21:13.35), the message I get is: "Server is Busy"

**Comment by LinLL** [comment]
I uesed the https://api.bithumb.com/info/orders API can get the information of my order ,but I can't cancel ,Are you seccuseed?

**Comment by jihoonerd** [comment]
I tried cancellation before and it worked at that time. It would be helpful to refer [order_ask](https://github.com/jihoon1990/Coiner/blob/bdded5320a6033f060ea73f02caed3b18e152a15/trader/trader.py#L190) method because I used the similar way to cancel orders.

**Comment by LinLL** [comment]
Good Luck. I tried a lot of times ,the platform give me failed. Now it works off. Thanks for your help.
